---
AWSTemplateFormatVersion: '2010-09-09'
Description:
  This creates a role with SecurityAudit policy attached to it.
Parameters:
  env:
    Description: The environment to deploy to
    Type: String
Resources:
  SecurityAuditor:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: 'auditor-cloudsec-${env}'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/SecurityAudit"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::697842321621:root"
            Action:
              - "sts:AssumeRole"